version: '3.4'

services:
  bds:
    image: enzo
    environment:
      EULA: "TRUE"
      GAMEMODE: creative
      DIFFICULTY: easy
    ports:
      - 18888:18888/udp
    volumes:
      - bds:/data
    stdin_open: true
    tty: true

volumes:
  bds: {}